# Generated by Django 3.2 on 2023-06-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True, null=True)),
                ('updated_up', models.DateTimeField(auto_now=True, null=True)),
                ('created_up', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
